[package]
name = "middleauth-ssh-proxy"
description = "MiddleAuth SSH Proxy"
authors = [
    "Brynn Warner <brynn@whitedogcyber.com>"
]
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "4.6"
directories = "6.0"
ssh-key = { version = "0.6", features = ["alloc"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "1.1.6"
reqwest = { version = "0.13", features = ["json"] }
keyring = { version = "4.2" }

tokio = { version = "1", features = ["full"] }
openidconnect = {  version = "4.0", features = ["reqwest"] }
url = "2.5"
axum = "0.8" # Lightweight loopback listener
open = "5.1" # Launches the default system browser